name: ldte_stei_itb
description: "Website pembuatan berbagai formulir Lab Dasar Sekolah Teknik Elektro dan Informatika Institut Teknologi Bandung"
publish_to: 'none'
version: 0.1.6+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.3.0
  get: ^4.7.3
  get_storage: ^2.1.1
  http: ^1.6.0
  cached_network_image: ^3.4.1
  dropdown_flutter: ^1.0.3
  auto_hide_keyboard: ^1.1.0
  omni_datetime_picker: ^2.3.1
  pdf: ^3.12.0
  google_fonts: ^8.0.2
  printing: ^5.14.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - fonts/
sets:
    - assets/
    - fonts/ assets/
    - fonts/